fix(android): image-crop openAsset signature diff
Resolves error related to:
```
error: method openAsset in class AndroidProtocolHandler cannot be applied to given types;
required: String
found: String,String
reason: actual and formal argument lists differ in length
```